spring.application.name=testes-spring-ai

logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
spring.ai.google.genai.api-key=${GENAI_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash
logging.level.org.springframework.ai.chat.client.advisor=DEBUG